name: Maven Publish (Releases)
on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  build:
    uses: srnyx/tools/.github/workflows/maven_publish.yml@main
    with:
      name: Event Alerts Java SDK
      channel: releases
    secrets:
      MAVEN_NAME: ${{ secrets.MAVEN_NAME }}
      MAVEN_SECRET: ${{ secrets.MAVEN_SECRET }}
